# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20161222171855) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "countries", force: :cascade do |t|
    t.string  "name"
    t.integer "ag_pct"
    t.integer "adult_hiv"
    t.integer "age_marriage"
    t.integer "empl_rate"
    t.integer "unempl_rate"
    t.integer "aid_given"
    t.integer "aid_received"
    t.integer "alcohol_consumption"
    t.integer "hiv_deaths"
    t.integer "army"
    t.integer "births_staffed"
    t.integer "bmi_m"
    t.integer "bmi_w"
    t.integer "breast_c"
    t.integer "cell_phones"
    t.integer "cervical_c"
    t.integer "child_mort"
    t.integer "children_pw"
    t.integer "co2_pp"
    t.integer "coal_pp"
    t.integer "colon_c_m"
    t.integer "colon_c_w"
    t.integer "debt_for"
    t.integer "dem_s"
    t.integer "elec_gen_pp"
    t.integer "elec_use_pp"
    t.integer "exp_prim"
    t.integer "exp_sec"
    t.integer "exp_tert"
    t.integer "exports"
    t.integer "ext_pov"
    t.integer "workers_f"
    t.integer "empl_rate_f"
    t.integer "food_supply"
    t.integer "forest_a"
    t.integer "forest_cov"
    t.integer "gdp_pp"
    t.integer "gdp_growth"
    t.integer "gdp_growth_tenyr"
    t.integer "gni_pp"
    t.integer "govt_health_exp"
    t.integer "govt_health_exp_pp"
    t.integer "hdi"
    t.integer "imp_san_acc"
    t.integer "imports"
    t.integer "inc_top_ten"
    t.integer "inc_bot_ten"
    t.integer "industry"
    t.integer "inequality"
    t.integer "inf_mort"
    t.integer "inflation"
    t.integer "int_users"
    t.integer "life_exp"
    t.integer "lit_f"
    t.integer "lit_m"
    t.integer "liver_c_m"
    t.integer "liver_c_f"
    t.integer "lung_c_m"
    t.integer "lung_c_f"
    t.integer "malaria"
    t.integer "empl_rate_m"
    t.integer "malnut"
    t.integer "mat_mort"
    t.integer "edu_yr_m"
    t.integer "edu_yr_f"
    t.integer "med_age"
    t.integer "doctors"
    t.integer "mil_exp"
    t.integer "murder"
    t.integer "nat_gas_prod"
    t.integer "oil_con_pp"
    t.integer "oil_prod"
    t.integer "oil_proved"
    t.integer "comp_pp"
    t.integer "pop_den"
    t.integer "pop_growth"
    t.integer "pop_urb"
    t.integer "pov"
    t.integer "prostate_c"
    t.integer "pump_gas"
    t.integer "sex_rat"
    t.integer "smoking"
    t.integer "stomach_c_m"
    t.integer "stomach_c_f"
    t.integer "sugar_pp"
    t.integer "suicide"
    t.integer "suicide_m"
    t.integer "suicide_f"
    t.integer "area"
    t.integer "tax"
    t.integer "trad_bal"
    t.integer "traffic_d"
    t.integer "wrk_hr"
    t.string  "pop"
  end

end
